
workflows:
  ios-native-workflow:
    name: iOS Native
    triggering:
      events:
        - push
    max_build_duration: 120
    instance_type: mac_mini_m1 
    environment:
      groups:
        - app_store_credentials
        - browserstack_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.thinkresearch.app
      vars:
        BUNDLE_ID: "com.thinkresearch.app"
        XCODE_WORKSPACE: "NativeSdkTest.xcworkspace"
        XCODE_SCHEME: "NativeSdkTest"
        APP_STORE_APPLE_ID: "6479017566"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          pod install --repo-update
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number $APP_APPLE_ID)
          echo "Updated version number $LATEST_BUILD_NUMBER"
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
      - name: Prepare BrowserStack Config
        script: |
          sed -i '' -e "s/\${userName}/${userName}/g" appium_tests/ios/browserstack.yml
          sed -i '' -e "s/\${accessKey}/${accessKey}/g" appium_tests/ios/browserstack.yml
      - name: Prepare pytest app config
        script: |
          sed -i '' -e "s/\${apiKey}/${app_api_key}/g" appium_tests/ios/pytest_main.yml
          sed -i '' -e "s/\${serverURL}/${app_server_url}/g" appium_tests/ios/pytest_main.yml
      - name: Upload ipa to BrowserStack
        script: |
          response=$(curl -u "${userName}:${accessKey}" \
          -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
          -F "file=@./build/ios/ipa/NativeSdkTest.ipa" \
          -F "custom_id=trc-skeleton-app-ios") 
      - name: Install BrowserStack SDK and Run Tests
        script: |
          cd ./appium_tests/ios
          pip install browserstack-sdk
          browserstack-sdk pytest pytest_main.py
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - sts@architech.ca
          - mnaseem@architech.ca
          - jtenneti@architech.ca
          - babiraman@architech.ca
          - emacius@architech.ca
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

        beta_groups:
          - external  
        submit_to_app_store: false
